//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrayEFProject.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    
    public partial class sorted_arrays
    {
		[Key]
        public int sorted_array_id { get; set; }
        public int array_id { get; set; }
        public float sorting_time { get; set; }
		[Required]
		[MaxLength(50)]
        public string sorter_name { get; set; }
		[Required]
        public string array_content { get; set; }
    
        public virtual input_arrays input_arrays { get; set; }
    }
}
